### ISSUE TITLE
[BUG] Custom Rarity Not Working

### ISSUE THREAD

**Issue by SnowyStarfall** [ProvidenceMod/ProvidenceMod#6]
**Describe the bug**
Applying a custom rarity by overriding the color of the ItemName in its tooltip is nonfunctional

**To Reproduce**

1. Go to your item
2. Apply a value from our Rarity enum in the SetDefaults(), like this:
```csharp
public override void SetDefaults()
{
  item.Providence().customRarity = (int) ProvidenceRarity.Celestial;
}
```
3. Examine the ModifyTooltips method on our ProvidenceGlobalItem
4. See the switch statement
5. Compile the mod ingame, the tooltip color remains unchanged

**Expected behavior**
It should, in theory, change the color of the tooltip.

**Version**
0.2.3.8

**Additional context**
It works if you instead check if the item type equals the type of the item that you want to change the tooltip of. Confusingly, it also seems to be setting the **customRarity** value, but **it is not triggering the ModifyTooltips code**. It also seems that the **ProvidenceRarity file shouldn't be causing the issue**, since I've tried assigning normal integers instead of values held within that enum and it still hasn't worked. However, **it does work if you set customRarity within the ProvidenceGlobalItem**. There seems to be some kind of **disconnect between setting the customRarity through the item defaults, and setting it within the ProvidenceGlobalItem**. After some logging, I did find that **setting it through the defaults still sets the value, but it does not execute the tooltips code**. I also found that reordering the code within the tooltips method doesn't work.

**Comment by SnowyStarfall** [comment]
After some more testing, I have found that the value is set within the ProvidenceGlobalItem. It is, for some reason, not executing the code to modify tooltips. At least, it is not executing the switch statement and the code it contains.

**Comment by ZackFox0** [comment]
Issue is fixed. Turns out we don't need the customRarity value; we can just use the vanilla item.rare, and assign it to an unused number. From there all the code works.
Not entirely sure why. Maybe an instancing issue?
